### ISSUE TITLE
"gcc": executable file not found in %PATH%

### ISSUE THREAD

**Issue by ghanavati27** [aakselrod/lnd#1]
![bitcoind-backend](https://user-images.githubusercontent.com/33449079/34326818-d6693b80-e8f0-11e7-87f2-d65c3523ce63.png)
I got this error

**Comment by ghanavati27** [comment]
I installed "gcc" , now i see new error.
# github.com/lightningnetwork/lnd/vendor/github.com/pebbe/zmq4
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

**Comment by aakselrod** [comment]
This has been fixed by switching to a pure Go library for ZMQ notification subscriptions.
